# Generated by Django 4.2.1 on 2023-05-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_field1', models.IntegerField()),
                ('numeric_field2', models.IntegerField()),
                ('numeric_field3', models.IntegerField()),
                ('text_field1', models.TextField()),
                ('text_field2', models.TextField()),
                ('date_field', models.DateField()),
            ],
        ),
    ]
